import 'dotenv/config';
//FILE CHỨA HẰNG SỐ DÙNG CHUNG LẤY TỪ .ENV
export const DATABASE_URL = process.env.DATABASE_URL;

export const REDIS_URL = process.env.REDIS_URL;

export const JWT_SECRET_KEY = process.env.JWT_SECRET;

export const JWT_REFRESH_SECRET_KEY = process.env.JWT_REFRESH_SECRET;

export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;

export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;

export const ELASTISEARCH_USERNAME = process.env.ELASTICSEARCH_USERNAME;

export const ELASTISEARCH_PASSWORD = process.env.ELASTICSEARCH_PASSWORD;

export const ELASTISEARCH_NODE = process.env.ELASTICSEARCH_NODE;

console.log(
    '\n',
    {
        DATABASE_URL: DATABASE_URL,
        REDIS_URL: REDIS_URL,
        ACCESS_TOKEN_SECRET: JWT_SECRET_KEY,
        REFRESH_TOKEN_SECRET: JWT_REFRESH_SECRET_KEY,
        GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
        ELASTICSEARCH_USERNAME: ELASTISEARCH_USERNAME,
        ELASTICSEARCH_PASSWORD: ELASTISEARCH_PASSWORD,
        ELASTICSEARCH_NODE: ELASTISEARCH_NODE,
    },
    '\n',
);
